package no.nav.eessi.pensjon.listeners.fagmodul

import java.time.LocalDate

object EessiFellesDto { // brukes kun for namespace.
    enum class EessiSakType { AFP, AFP_PRIVAT, ALDER, BARNEP, FAM_PL, GAM_YRK, GENRL, GJENLEV, GRBL, KRIGSP, OMSORG, UFOREP }
    enum class EessiSakStatus { TIL_BEHANDLING, INGEN_STATUS, OPPRETTET, UKJENT, TRUKKET, AVBRUTT, AVSL, INNV, OPPHOR, VELG, VETIKKE, ANNET, EESSI_INGEN_STATUS, EESSI_UKJENT, EESSI_AVBRUTT, LOPENDE }
    enum class EessiKravAarsak { AFP_EO, ALDERSOVERGANG, ANNEN_ARSAK, ANNEN_ARSAK_END_IN, ANNEN_FOR_END_IN, ANNET, AVSLAG, AVSLAG_INVAL_ENKEP, AVSLAG_UNG_UFR, AVSLAG_UT, BARNETILLEGG, BARN_DOD,
        BARN_ENDRET_INNTEKT, BARN_UTDS_FLYTTEUTG, BEGGE_FOR_END_IN, BEREGNING, BODD_ARB_UTL, EKSPORT, EKTEFELLETILLEGG, ENDRET_INNTEKT, ENDRET_OPPTJENING, ENDRING_IFU,
        ENDR_ANNEN_SAK, EPS_ENDRET_INNTEKT, EPS_NY_YTELSE, EPS_NY_YTELSE_UT, EPS_OPPH_YTELSE_UT, ETTEROPPGJOR, GJENLEVENDERETT, GJENLEVENDETILLEGG, GJNL_SKAL_VURD, GODSKR_OVERF,
        GOMR, GRADSENDRINGER, HJEMMEBER_FOR_UT, HVIL_STONADSRETT, INNT_KONTROLL, INNVANDRET, INSTOPPHOLD, KLAGE_ANKE, KONTR_3_17, LOVVALG, MEDISINSK_STONAD, MEDL_TRYGDETID,
        MEDL_TRYGDETID_OPPTJ, NYE_OPPLYSNINGER, NY_SOKNAD, OMGJ_ETTER_ANKE, OMGJ_ETTER_FVL_P35_A, OMGJ_ETTER_FVL_P35_B, OMGJ_ETTER_FVL_P35_C, OMGJ_ETTER_KLAGE, OMREGNING, OMREGN_UFORETRYGD,
        OMR_FEILRETTING, OMSORG_FOR_SMA_BARN, OPPHOR, OPPHOR_HJELPELOS, OPPHOR_REDUKSJON, OPPHOR_RED_UFG, OPPHOR_TLG_HJELP_HUS, OPPL_UTLAND, OPPTJENINGSGRUNNLAG,
        OVERGANGSSTONAD, OVRFR_OMSORGSPOENG, PENSJONSVILKAR, PLEIE_ELDR_SYK_FUNK, REGULERING, REKONSTRUKSJON, SAMORDNING, SIVILSTANDSENDRING, SOKNAD_BT, TIDLIGUTTAK, TILBAKEKREVING,
        TILSTOT_ENDR_YTELSE, TILSTOT_OPPHORT, TILST_DOD, TVUNGEN_FORVALTNING, UFG_IFU_OG_IEU, UFOREBER_V_GTGRD, UFOREBER_V_TIDUFT, UFOREOVERGANG, UFR_GRAD, UFR_PENSJON_GRAD, UFR_TIDSPUNKT, UTBET_AVKORT,
        UTTAKSGRAD, UTVANDRET, UT_EO, UT_OMGJ_ANKE_EO, UT_OMGJ_KLAGE_EO, UT_VURDERING_EO, VILKAR, VIRK_TIDSPUNKT, VURDER_FORSORG, VURDER_SERSKILT_SATS, VURD_SIVILST, YRKESSKADE, YRK_SKADE_SYK }

    // pensjon-pen:no.nav.pensjon.pen_app.domain.eessi.dto.EessiKravGjelder
    enum class EessiKravGjelder { AFP_EO, ANKE, EKSPORT, ENDR_UTTAKSGRAD, ERSTATNING, ETTERGIV_GJELD, FAS_UTG_IO, FORSTEG_BH,
        F_BH_BO_UTL, F_BH_KUN_UTL, F_BH_MED_UTL, GJ_RETT, GOD_OMSGSP, GOMR, HJLPBER_OVERG_UT, INNT_E,
        INNT_KTRL, KLAGE, KONTROLL_3_17_A, KONVERTERING, KONVERTERING_MIN, KONV_AVVIK_G_BATCH, MELLOMBH, MTK,
        OMGJ_TILBAKE, OVERF_OMSGSP, REGULERING, REVURD, SAK_OMKOST, SLUTT_BH_UTL, SOK_OKN_UG, SOK_RED_UG,
        SOK_UU, SOK_YS, TILBAKEKR, UT_EO, UT_VURDERING_EO, UTSEND_AVTALELAND, SLUTTBEH_KUN_UTL }

    data class PensjonSakDto(val sakId: String, val sakType: EessiSakType, val sakStatus: EessiSakStatus)
    data class EessiAvdodDto(val avdod: String?, val avdodMor: String?, val avdodFar: String?)
    data class EessiUfoeretidspunktDto(val uforetidspunkt: LocalDate?, val virkningstidspunkt: LocalDate?)
}
