package no.nav.eessi.pensjon.journalforing.services.oppgave

import no.nav.eessi.pensjon.journalforing.services.oppgave.OppgaveRoutingModel.Enhet.*

data class OppgaveRoutingModel(
        var bucType: BucType,
        var fnr: String?,
        var bosatt: Bosatt
) {
    enum class BucType(val bosattNorgeEnhet: Enhet, val manglerFnrEnhet: Enhet, val bosattUtlandEnhet: Enhet) {
        P_BUC_01(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_02(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_03(UFORE_UTLANDSTILSNITT, UFORE_UTLANDSTILSNITT, UFORE_UTLAND),
        P_BUC_04(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_05_NFP_KRETS(UFORE_UTLANDSTILSNITT, UFORE_UTLANDSTILSNITT, UFORE_UTLAND) ,
        P_BUC_05_NAY_KRETS(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_06_NFP_KRETS(UFORE_UTLANDSTILSNITT, UFORE_UTLANDSTILSNITT, UFORE_UTLAND),
        P_BUC_06_NAY_KRETS(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_07_NFP_KRETS(UFORE_UTLANDSTILSNITT, UFORE_UTLANDSTILSNITT, UFORE_UTLAND),
        P_BUC_07_NAY_KRETS(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_08_NFP_KRETS(UFORE_UTLANDSTILSNITT, UFORE_UTLANDSTILSNITT, UFORE_UTLAND),
        P_BUC_08_NAY_KRETS(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_09_NFP_KRETS(UFORE_UTLANDSTILSNITT, UFORE_UTLANDSTILSNITT, UFORE_UTLAND),
        P_BUC_09_NAY_KRETS(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_10_AP(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_10_GP(NFP_UTLAND_AALESUND, NFP_UTLAND_AALESUND, PENSJON_UTLAND),
        P_BUC_10_UT(UFORE_UTLANDSTILSNITT, NFP_UTLAND_AALESUND, UFORE_UTLAND),
    }

    enum class Bosatt {
        NORGE ,
        UTLAND
    }

    enum class Enhet(val enhetsNr : String) {
        PENSJON_UTLAND("0001"),
        UFORE_UTLANDSTILSNITT("4476"),
        UFORE_UTLAND("4475"),
        NFP_UTLAND_AALESUND("4862")
    }
}
