kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-journalforing-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  envFrom:
    - secret: journalforing-dev
  azure:
    application:
      enabled: true
    accessPolicy:
      outbound:
        external:
          - host: https://eessi-pensjon-journalforing-q2.dev.intern.nav.no
  webproxy: true

  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: NAMESPACE
      value: q2
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api-q2.nais.preprod.local/cpi
    - name: PDL_URL
      value: https://pdl-api.dev-fss.nais.io/graphql
    - name: JOURNALPOST_V1_URL
      value: https://dokarkiv-q2.nais.preprod.local/rest/journalpostapi/v1
    - name: OPPGAVE_OPPGAVER_URL
      value: https://oppgave-q2.nais.preprod.local/api/v1/oppgaver
    - name: AKTOERREGISTER_API_V1_URL
      value: https://app-q2.adeo.no/aktoerregister/api/v1
    - name: EESSI_PENSJON_FAGMODUL_URL
      value: https://eessi-pensjon-fagmodul-q2.nais.preprod.local/
    - name: NORG2_URL
      value: https://app-q4.adeo.no/norg2/
    - name: BESTEMSAK_URL
      value: https://pensjon-pen-q2.nais.preprod.local/pen/api/bestemsak/v1
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessi-basis-sedSendt-v1-q2
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessi-basis-sedMottatt-v1-q2
    - name: KAFKA_OPPGAVE_TOPIC
      value: eessipensjon.privat-oppgave-q2
    - name: KAFKA_KRAV_TOPIC
      value: eessipensjon.privat-krav-initialisering-q2
    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering-q2
    - name: AZURE_APP_EUX_CLIENT_ID
      value: dev-fss.eessibasis.eux-rina-api-q2
    - name: AZURE_APP_PEN_CLIENT_ID
      value: dev-fss.teampensjon.pensjon-pen-q2
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-journaforing-q2.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi