kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-journalforing-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  envFrom:
    - secret: journalforing-dev
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: etterlatte-api
          namespace: etterlatte
          cluster: dev-gcp
      external:
        - host: norg2.dev-fss-pub.nais.io
        - host: saf-q2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: navansatt.dev-fss-pub.nais.io
        - host: dokarkiv-q2.dev-fss-pub.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: eux-rina-api-gcp-q2.intern.dev.nav.no
        - host: eessi-pensjon-oppgave-q2.intern.dev.nav.no
        - host: eessi-pensjon-fagmodul-q2.intern.dev.nav.no
  webproxy: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: NAMESPACE
      value: q2
    - name: GCP_BUCKET_NAME_GJENNY
      value: eessi-pensjon-gjenny-dev

    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api-gcp-q2.intern.dev.nav.no/cpi
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: JOURNALPOST_V1_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io/rest/journalpostapi/v1
    - name: SAF_GRAPHQL_URL
      value: https://saf-q2.dev-fss-pub.nais.io/graphql
    - name: EESSI_PENSJON_FAGMODUL_URL
      value: https://eessi-pensjon-fagmodul-q2.intern.dev.nav.no
    - name: NORG2_URL
      value: https://norg2.dev-fss-pub.nais.io/norg
    - name: BESTEMSAK_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io/pen/api/bestemsak/v1
    - name: NAVANSATT_URL
      value: https://navansatt.dev-fss-pub.nais.io
    - name: ETTERLATTE_URL
      value: http://etterlatte-api.etterlatte

    - name: KAFKA_SEDSENDT_TOPIC
      value: eessibasis.sedsendt-v1-q2
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1-q2
    - name: KAFKA_OPPGAVE_TOPIC
      value: eessipensjon.privat-oppgave-q2
    - name: KAFKA_KRAV_TOPIC
      value: eessipensjon.privat-krav-initialisering-q2
    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering-q2

    - name: AZURE_APP_FAGMODUL_CLIENT_ID
      value: dev-gcp.eessipensjon.eessi-pensjon-fagmodul-q2
    - name: AZURE_APP_EUX_CLIENT_ID
      value: dev-gcp.eessibasis.eux-rina-api-q2
    - name: AZURE_APP_NORG2_CLIENT_ID
      value: dev-fss.org.norg2
    - name: AZURE_APP_NAVANSATT_CLIENT_ID
      value: dev-fss.teampensjon.navansatt
    - name: AZURE_APP_PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: AZURE_APP_DOKARKIV_CLIENT_ID
      value: dokarkiv
    - name: AZURE_APP_SAF_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.saf
    - name: AZURE_APP_ETTERLATTE_CLIENT_ID
      value: dev-gcp.etterlatte.etterlatte-api
    - name: AZURE_APP_PEN_CLIENT_ID
      value: dev-fss.pensjon-q2.pensjon-pen-q2

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-journaforing-q2.intern.dev.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi