kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-journalforing
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  envFrom:
    - secret: journalforing-prod
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: prod-fss.eessipensjon.eessi-pensjon-onprem-proxy
        - host: eessi-pensjon-fagmodul.intern.nav.no
        - host: eessi-pensjon-oppgave.intern.nav.no
        - host: eux-rina-api.prod-fss-pub.nais.io
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: norg2.prod-fss-pub.nais.io
        - host: navansatt.prod-fss-pub.nais.io
  webproxy: true
  gcp:
    buckets:
      - name: eessi-pensjon-journal
        retentionPeriodDays: 40
        lifecycleCondition:
          age: 365
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: NAMESPACE
      value: p
    - name: GCP_BUCKET_NAME_JOURNAL
      value: eessi-pensjon-journal
    - name: GCP_BUCKET_NAME_GJENNY
      value: eessi-pensjon-gjenny
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api.prod-fss-pub.nais.io/cpi
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: JOURNALPOST_V1_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1
    - name: EESSI_PENSJON_FAGMODUL_URL
      value: https://eessi-pensjon-fagmodul.intern.nav.no
    - name: NORG2_URL
      value: https://norg2.prod-fss-pub.nais.io/norg2
    - name: BESTEMSAK_URL
      value: https://eessi-pensjon-onprem-proxy.prod-fss-pub.nais.io/pen/api/bestemsak/v1
    - name: NAVANSATT_URL
      value: https://navansatt.prod-fss-pub.nais.io
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy.prod-fss-pub.nais.io
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessibasis.sedsendt-v1
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1
    - name: KAFKA_OPPGAVE_TOPIC
      value: eessipensjon.privat-oppgave
    - name: KAFKA_KRAV_TOPIC
      value: eessipensjon.privat-krav-initialisering
    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering
    - name: AZURE_APP_FAGMODUL_CLIENT_ID
      value: prod-gcp.eessipensjon.eessi-pensjon-fagmodul
    - name: AZURE_APP_EUX_CLIENT_ID
      value: prod-fss.eessibasis.eux-rina-api
    - name: AZURE_APP_NORG2_CLIENT_ID
      value: prod-fss.org.norg2
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: prod-fss.eessipensjon.eessi-pensjon-onprem-proxy
    - name: AZURE_APP_PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: AZURE_APP_DOKARKIV_CLIENT_ID
      value: dokarkiv
    - name: AZURE_APP_NAVANSATT_CLIENT_ID
      value: prod-fss.pensjondeployer.navansatt

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-journaforing.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 2Gi