
# ******************************************************************************************************************
#
# Dette er en auto-generert fil; endringer gjøres i templates/.github/workflows/deploy_prod.yml
# Kjør deretter ' make generate-files' for oppdatering av workflow hos prosjekter
#
# ******************************************************************************************************************

name: Deploy PROD
on:
  repository_dispatch:
    types: [deploy-prod]

jobs:
  deploy_prod:
    name: 'Deploy til PROD'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v3

      - name: 'Vise image'
        run: |
          echo "image-tag: ${{ github.event.client_payload.image }}"

      - name: 'NAIS-deploy to PROD'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-gcp.yml
          IMAGE: ${{ github.event.client_payload.image }}
