# Kan slettes når testing av PDL er ferdig
name: Deploy Q2
on:
  push:
    branches:
      - feature/PDL
jobs:
  tag_deploy_q2:
    name: 'Deploy til Q2'
    runs-on: ubuntu-latest
    steps:
      # GET version
      - name: 'Get the version'
        uses: actions/checkout@v2

      # Show IMAGE from Q2 deploy
      - name: 'Vise image'
        run: |
          echo "image-tag: ${{ github.event.client_payload.image }}"

      - name: 'NAIS-deploy to Q2'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss-q2.yml
          VARS: nais/dev-fss-q2.json
          IMAGE: ${{ github.event.client_payload.image }}
