name: Deploy PROD
on:
  repository_dispatch:
    types: [deploy-prod]
jobs:
  tag_deploy_q1:
    name: 'Deploy til PROD'
    runs-on: ubuntu-latest
    steps:
      # GET version
      - name: 'Get the version'
        uses: actions/checkout@v2

      # Show IMAGE from Q2 deploy
      - name: 'Vise image'
        run: |
          echo "image-tag: ${{ github.event.client_payload.image }}"

      - name: 'NAIS-deploy to PROD'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/prod-fss.yml
          VARS: nais/prod-fss.json
          IMAGE: ${{ github.event.client_payload.image }}
