
# ******************************************************************************************************************
#
# Dette er en auto-generert fil; endringer gjøres i templates/.github/workflows/dispatch_issue_comment.yml
# Kjør deretter ' make generate-files' for oppdatering av workflow hos prosjekter
#
# ******************************************************************************************************************

name: Slash command dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          commands: prodsett